from typing import List, Dict, Any, TypedDict, Annotated, Optional
import operator

def merge_usage(left: Dict[str, int], right: Dict[str, int]) -> Dict[str, int]:
    if not left: return right
    if not right: return left
    new_usage = left.copy()
    for k, v in right.items():
        new_usage[k] = new_usage.get(k, 0) + v
    return new_usage

class AgentState(TypedDict):
    """
    State for the Regle Master Orchestrator with Planning & Routing.
    """
    mode: str                  # User selected mode: 'rag', 'web', or 'hybrid'
    question: str
    project_id: Optional[str]   # Specific research project identity
    user_id: Optional[str]      # User identity for vector isolation
    plan: List[str]            # The 3-step reasoning plan generated by the LLM
    plan_str: str              # String version of the plan for routing logic
    next_step: str             # Which node to hit next (determined by router)
    raw_documents: Annotated[List[Dict[str, Any]], operator.add]
    filtered_documents: List[Dict[str, Any]]
    generation: str
    search_needed: bool
    total_usage: Annotated[Dict[str, int], merge_usage]
    steps: Annotated[List[str], operator.add]
    grades: Annotated[List[Dict[str, Any]], operator.add]
