/**
 * Regle LaTeX Exporter Utility
 * Converts Regle-flavored Markdown into a professional academic LaTeX document.
 */
export const convertToLaTeX = (content: string, title?: string): string => {
  const docTitle = title || "REGLE_RESEARCH_REPORT";
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  let latex = `\\documentclass[11pt,a4paper]{article}

% --- PREAMBLE ---
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{lmodern}
\\usepackage[margin=1in]{geometry}
\\usepackage{amsmath,amssymb}
\\usepackage{booktabs}
\\usepackage{pgfplots}
\\usepackage{pgf-pie}
\\usepackage{hyperref}
\\usepackage{color}
\\usepackage{graphicx}

\\pgfplotsset{compat=1.18}
\\hypersetup{colorlinks=true, linkcolor=blue, urlcolor=blue}

% --- TITLE & AUTHOR ---
\\title{${docTitle}}
\\author{Project Genesis Orbital Engine}
\\date{${date}}

\\begin{document}

\\maketitle

\\begin{abstract}
This document contains an expert research synthesis generated by the Regle Orchestration Engine. It includes high-fidelity data visualizations and multi-modal analytical summaries.
\\end{abstract}

`;

  // --- CONTENT CONVERSION ---
  let lines = content.split('\n');
  let inTable = false;
  let tableRows: string[][] = [];

  for (let i = 0; i < lines.length; i++) {
    let line = lines[i].trim();

    // 1. Headings
    if (line.startsWith('# ')) {
      latex += `\\section{${line.replace('# ', '').trim()}}\n\n`;
      continue;
    }
    if (line.startsWith('## ')) {
      latex += `\\subsection{${line.replace('## ', '').trim()}}\n\n`;
      continue;
    }
    if (line.startsWith('### ')) {
      latex += `\\subsubsection{${line.replace('### ', '').trim()}}\n\n`;
      continue;
    }

    // 2. Bold/Italics
    line = line.replace(/\*\*(.*?)\*\*/g, '\\textbf{$1}');
    line = line.replace(/\*(.*?)\*/g, '\\textit{$1}');

    // 3. LaTeX / TikZ Code Blocks (Unescape and include)
    if (line.startsWith('```latex') || line.startsWith('```tikz')) {
      let block = "";
      i++;
      while (i < lines.length && !lines[i].trim().startsWith('```')) {
        block += lines[i] + "\n";
        i++;
      }
      latex += block + "\n";
      continue;
    }

    // 4. Other Code Blocks (Verbatim)
    if (line.startsWith('```')) {
      latex += "\\begin{verbatim}\n";
      i++;
      while (i < lines.length && !lines[i].trim().startsWith('```')) {
        latex += lines[i] + "\n";
        i++;
      }
      latex += "\\end{verbatim}\n\n";
      continue;
    }

    // 5. GFM Tables (Simplified Conversion)
    if (line.startsWith('|')) {
      if (!inTable) {
        inTable = true;
        tableRows = [];
      }
      // Extract cells
      const cells = line.split('|').filter(c => c.trim() !== "").map(c => c.trim());
      if (cells.length > 0 && !line.includes('---')) {
        tableRows.push(cells);
      }
      continue;
    } else if (inTable) {
      // Close table
      if (tableRows.length > 0) {
        const colCount = tableRows[0].length;
        const colSpec = "l".repeat(colCount);
        latex += `\\begin{table}[h!]
\\centering
\\begin{tabular}{${colSpec}}
\\toprule
${tableRows[0].join(' & ')} \\\\ \n\\midrule\n`;
        for (let j = 1; j < tableRows.length; j++) {
           latex += `${tableRows[j].join(' & ')} \\\\ \n`;
        }
        latex += `\\bottomrule
\\end{tabular}
\\caption{Generated analytical data table.}
\\end{table}\n\n`;
      }
      inTable = false;
      tableRows = [];
    }

    // 6. Math
    // (Handled by the fact that $...$ and $$...$$ are already valid LaTeX)
    
    // 7. Regular Lines
    if (line !== "") {
      latex += line + "\n\n";
    }
  }

  // Finalize table if text ends with one
  if (inTable && tableRows.length > 0) {
    const colCount = tableRows[0].length;
    const colSpec = "l".repeat(colCount);
    latex += `\\begin{table}[h!]
\\centering
\\begin{tabular}{${colSpec}}
\\toprule
${tableRows[0].join(' & ')} \\\\ \n\\midrule\n`;
    for (let j = 1; j < tableRows.length; j++) {
       latex += `${tableRows[j].join(' & ')} \\\\ \n`;
    }
    latex += `\\bottomrule
\\end{tabular}
\\end{table}\n\n`;
  }

  latex += "\n\\end{document}";
  return latex;
};
